### ISSUE TITLE
unable to encode JP text back into the game

### ISSUE THREAD

**Issue by robby-unruh** [biribiribiri/fragment#1]
leaving partial text untranslated causes an issue with encoding JP characters back into the game. i'm pretty sure you already know this is a shift+jis issue.

![error-1](https://user-images.githubusercontent.com/9296352/76168264-6f3a8d00-6144-11ea-919e-1a5875a280a3.png)

**Comment by biribiribiri** [comment]
Should be fixed in https://github.com/biribiribiri/fragment/releases/tag/0.0.2
